feat(aidd): experimental

diff --git a/.scripts/catai b/.scripts/catai
--- a/.scripts/catai
+++ b/.scripts/catai
@@ -1,16 +1,20 @@
 #!/bin/bash
 
+command -v fzf &> /dev/null || echo "fzf required. Installation: brew install fzf"
+
 process_files() {
   while IFS= read -r file; do
+    local ext=$(basename $file | rev | cut -d. -f1 | rev)
     echo "File: $file"
-    echo '```'
+    echo "\`\`\`$ext"
     cat -n "$file"
     echo '```'
+    echo
   done <<< "$1"
 }
 
 if [ $# -eq 0 ]; then
-  echo "Usage: catai [query | manual] [-]"
+  echo "Usage: catai [file extension | manual] [-]"
   exit 0
 fi
 
@@ -26,7 +30,8 @@ case "$option" in
 
     selected_files=$(
       echo "$files" \
-      | fzf --tmux -m --ansi --filepath-word \
+      | fzf --tmux \
+        -m --ansi --filepath-word \
         --preview='bat --theme=Dracula --color=always --style=numbers --line-range=:100 {}' \
         --bind ctrl-t:toggle-all
     )
@@ -41,7 +46,7 @@ case "$option" in
     ;;
 esac
 
-output=$(process_files "$selected_files")
+[[ ! -z "$selected_files" ]] && output=$(process_files "$selected_files")
 
 if [ -z "$2" ]; then
   [ "$(uname)" = "Darwin" ] && echo "$output" | pbcopy
